In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\sabav\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\sabav\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sabav\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\Users\sabav\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\Users\sabav\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in C:\Users\sabav\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("zomato.csv")

In [5]:
data.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [6]:
data.tail()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
51712,https://www.zomato.com/bangalore/best-brews-fo...,"Four Points by Sheraton Bengaluru, 43/3, White...",Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500","[('Rated 5.0', ""RATED\n Food and service are ...",[],Pubs and bars,Whitefield
51713,https://www.zomato.com/bangalore/vinod-bar-and...,"Number 10, Garudachar Palya, Mahadevapura, Whi...",Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600,[],[],Pubs and bars,Whitefield
51714,https://www.zomato.com/bangalore/plunge-sherat...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000",[],[],Pubs and bars,Whitefield
51715,https://www.zomato.com/bangalore/chime-sherato...,Sheraton Grand Bengaluru Whitefield Hotel & Co...,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500","[('Rated 4.0', 'RATED\n Nice and friendly pla...",[],Pubs and bars,Whitefield
51716,https://www.zomato.com/bangalore/the-nest-the-...,"ITPL Main Road, KIADB Export Promotion Industr...",The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500","[('Rated 5.0', 'RATED\n Great ambience , look...",[],Pubs and bars,Whitefield

In [10]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51717 entries, 0 to 51716
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   url                          51717 non-null  object
 1   address                      51717 non-null  object
 2   name                         51717 non-null  object
 3   online_order                 51717 non-null  object
 4   book_table                   51717 non-null  object
 5   rate                         43942 non-null  object
 6   votes                        51717 non-null  int64
 7   phone                        50509 non-null  object
 8   location                     51696 non-null  object
 9   rest_type                    51490 non-null  object
 10  dish_liked                   23639 non-null  object
 11  cuisines                     51672 non-null  object
 12  approx_cost(for two people)  51371 non-null  object
 13  reviews_list                 51717 non-null  object
 14  menu_item                    51717 non-null  object
 15  listed_in(type)              51717 non-null  object
 16  listed_in(city)              51717 non-null  object
dtypes: int64(1), object(16)
memory usage: 6.7+ MB

In [12]:
data.shape

(51717, 17)

In [13]:
"""Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Cleaning individual columns.
Remove the NaN values from the dataset
Check for some more Transformations"""

'Deleting redundant columns.\nRenaming the columns.\nDropping duplicates.\nCleaning individual columns.\nRemove the NaN values from the dataset\nCheck for some more Transformations'

In [14]:
data.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [78]:
columns_to_keep = ['name', 'online_order', 'book_table', 'rate','dish_liked','approx_cost(for two people)' ]
columns_to_drop = ['url', 'address','votes','phone', 'location', 'rest_type', 'cuisines', 'reviews_list', 'menu_item','listed_in(type)', 'listed_in(city)']

In [79]:
data.columns

Index(['name', 'online_order', 'book_table', 'rate', 'dish_liked',
       'approx_cost(for two people)'],
      dtype='object')

In [80]:
columns_to_keep

['name',
 'online_order',
 'book_table',
 'rate',
 'dish_liked',
 'approx_cost(for two people)']

In [81]:
columns_to_drop

['url',
 'address',
 'votes',
 'phone',
 'location',
 'rest_type',
 'cuisines',
 'reviews_list',
 'menu_item',
 'listed_in(type)',
 'listed_in(city)']

In [83]:
data.shape

(51717, 6)

In [84]:
len(columns_to_keep)

6

In [85]:
len(columns_to_drop)

11

#1st Way - Filtering Data

In [86]:
columns_to_keep

['name',
 'online_order',
 'book_table',
 'rate',
 'dish_liked',
 'approx_cost(for two people)']

In [87]:
modify_data = data[columns_to_keep]

In [88]:
modify_data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

#2nd way, dropping the columns

In [89]:
columns_to_drop

['url',
 'address',
 'votes',
 'phone',
 'location',
 'rest_type',
 'cuisines',
 'reviews_list',
 'menu_item',
 'listed_in(type)',
 'listed_in(city)']

In [99]:
data = pd.read_csv("zomato.csv")

In [100]:
columns_to_drop

['url',
 'address',
 'votes',
 'phone',
 'location',
 'rest_type',
 'cuisines',
 'reviews_list',
 'menu_item',
 'listed_in(type)',
 'listed_in(city)']

In [104]:
data.drop(columns = columns_to_drop, inplace = True)

In [105]:
data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [ ]:
"""Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Cleaning individual columns.
Remove the NaN values from the dataset
Check for some more Transformations""""""

In [110]:
data

,name1,online_order123,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [117]:
data.rename(columns = {"name1":'name',"online_order123": 'onlineorder'}, inplace = True)

In [118]:
data.columns

Index(['name', 'onlineorder', 'book_table', 'rate', 'dish_liked',
       'approx_cost(for two people)'],
      dtype='object')

In [119]:
data.columns[0].capitalize()

'Name'

In [121]:
 for i in data.columns:
    print(i.capitalize())

Name
Onlineorder
Book_table
Rate
Dish_liked
Approx_cost(for two people)

In [124]:
new_column_names = []
for i in data.columns:
    new_column_names.append(i.capitalize())

In [126]:
data.columns

Index(['name', 'onlineorder', 'book_table', 'rate', 'dish_liked',
       'approx_cost(for two people)'],
      dtype='object')

In [127]:
data.columns = new_column_names

In [128]:
new_column_names

['Name',
 'Onlineorder',
 'Book_table',
 'Rate',
 'Dish_liked',
 'Approx_cost(for two people)']

In [130]:
data

,Name,Onlineorder,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,NaN,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,NaN,"1,500"

In [131]:
data.columns

Index(['Name', 'Onlineorder', 'Book_table', 'Rate', 'Dish_liked',
       'Approx_cost(for two people)'],
      dtype='object')

In [ ]:
"""Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Cleaning individual columns.
Remove the NaN values from the dataset
Check for some more Transformations"""

In [133]:
data.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
51712     True
51713     True
51714    False
51715     True
51716     True
Length: 51717, dtype: bool

In [135]:
data.duplicated().sum()

np.int64(32808)

In [136]:
data.duplicated().value_counts()

True     32808
False    18909
Name: count, dtype: int64

In [138]:
data.duplicated().tail(10)

51707     True
51708     True
51709     True
51710     True
51711     True
51712     True
51713     True
51714    False
51715     True
51716     True
dtype: bool

In [140]:
data.drop_duplicates(inplace = True)

In [142]:
data.duplicated().sum()

np.int64(0)

In [ ]:
"""Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Cleaning individual columns.
Remove the NaN values from the dataset
Check for some more Transformations"""

In [144]:
data.isna()

,Name,Onlineorder,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
...,...,...,...,...,...,...
51631,False,False,False,False,True,False
51632,False,False,False,False,True,False
51641,False,False,False,False,True,True
51677,False,False,False,False,False,False
51714,False,False,False,True,True,False

In [145]:
data.isna().sum()

Name                               0
Onlineorder                        0
Book_table                         0
Rate                            2418
Dish_liked                     10587
Approx_cost(for two people)      140
dtype: int64

In [147]:
data.dropna()

,Name,Onlineorder,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51611,Chung Wah,No,No,2.5 /5,Manchow Soup,800
51617,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
51620,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
51677,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

In [149]:
data.dropna(inplace = True)

In [150]:
data.isna().sum()

Name                           0
Onlineorder                    0
Book_table                     0
Rate                           0
Dish_liked                     0
Approx_cost(for two people)    0
dtype: int64

In [153]:
data.index.name = "index"

In [154]:
data

,Name,Onlineorder,Book_table,Rate,Dish_liked,Approx_cost(for two people)
index,,,,,,
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51611,Chung Wah,No,No,2.5 /5,Manchow Soup,800
51617,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
51620,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
51677,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

In [155]:
data = data.reset_index().rename(columns={"index": "ID"})

In [156]:
data

,ID,Name,Onlineorder,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
8245,51611,Chung Wah,No,No,2.5 /5,Manchow Soup,800
8246,51617,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
8247,51620,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,51677,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

In [157]:
data.drop(columns = "ID", inplace = True)

In [158]:
data

,Name,Onlineorder,Book_table,Rate,Dish_liked,Approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,Yes,No,4.1/5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,Yes,No,3.8/5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,Masala Dosa,300
4,Grand Village,No,No,3.8/5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
8245,Chung Wah,No,No,2.5 /5,Manchow Soup,800
8246,Breakfast House,No,No,3.6 /5,"Coffee, Vada, Mla Dosa",300
8247,Fujian Express,Yes,No,3.8 /5,"Noodles, Chicken Noodle, Momos, American Chops...",600
8248,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 /5,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","1,800"
8249,Bhagini,No,No,2.5 /5,"Biryani, Andhra Meal",800

In [ ]:
"""Deleting redundant columns.
Renaming the columns.
Dropping duplicates.
Remove the NaN values from the dataset
Cleaning individual columns.
Check for some more Transformations"""

In [159]:
data["Rate"]

0        4.1/5
1        4.1/5
2        3.8/5
3        3.7/5
4        3.8/5
         ...
8245    2.5 /5
8246    3.6 /5
8247    3.8 /5
8248    4.2 /5
8249    2.5 /5
Name: Rate, Length: 8250, dtype: object

In [232]:
data["rate"] = data["rate"].str.replace(" ","")

In [233]:
data["rate"] = data["rate"].str.replace("/"," out of ")

In [237]:
data = data[columns_to_keep]

In [238]:
data

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,0,Yes,4.1outof5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,0,No,4.1outof5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,0,No,3.8outof5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7outof5,Masala Dosa,300
4,Grand Village,0,No,3.8outof5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,0,No,3.6outof5,NaN,"1,500"
51713,Vinod Bar And Restaurant,0,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,0,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,0,Yes,4.3outof5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,0,No,3.4outof5,NaN,"1,500"

In [239]:
data.to_csv("Cleaned_csv_file.csv")

In [240]:
pd.read_csv("Cleaned_csv_file.csv")

,Unnamed: 0,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,0,Jalsa,0,Yes,4.1outof5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,1,Spice Elephant,0,No,4.1outof5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,2,San Churro Cafe,0,No,3.8outof5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,3,Addhuri Udupi Bhojana,0,No,3.7outof5,Masala Dosa,300
4,4,Grand Village,0,No,3.8outof5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...,...
51712,51712,Best Brews - Four Points by Sheraton Bengaluru...,0,No,3.6outof5,NaN,"1,500"
51713,51713,Vinod Bar And Restaurant,0,No,NaN,NaN,600
51714,51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,0,No,NaN,NaN,"2,000"
51715,51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,0,Yes,4.3outof5,"Cocktails, Pizza, Buttermilk","2,500"
51716,51716,The Nest - The Den Bengaluru,0,No,3.4outof5,NaN,"1,500"

In [241]:
data.to_csv("Cleaned_csv_file_no_index.csv", index=False )

In [242]:
pd.read_csv("Cleaned_csv_file_no_index.csv")

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,0,Yes,4.1outof5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,0,No,4.1outof5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,0,No,3.8outof5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7outof5,Masala Dosa,300
4,Grand Village,0,No,3.8outof5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,0,No,3.6outof5,NaN,"1,500"
51713,Vinod Bar And Restaurant,0,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,0,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,0,Yes,4.3outof5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,0,No,3.4outof5,NaN,"1,500"

In [248]:
pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [249]:
data.to_excel("Cleaned_excel.xlsx")

In [250]:
data.to_excel("Cleaned_excel_no_index.xlsx", index = False)

In [251]:
pd.read_csv("Cleaned_csv_file_no_index.csv")

,name,online_order,book_table,rate,dish_liked,approx_cost(for two people)
0,Jalsa,0,Yes,4.1outof5,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...",800
1,Spice Elephant,0,No,4.1outof5,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...",800
2,San Churro Cafe,0,No,3.8outof5,"Churros, Cannelloni, Minestrone Soup, Hot Choc...",800
3,Addhuri Udupi Bhojana,0,No,3.7outof5,Masala Dosa,300
4,Grand Village,0,No,3.8outof5,"Panipuri, Gol Gappe",600
...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,0,No,3.6outof5,NaN,"1,500"
51713,Vinod Bar And Restaurant,0,No,NaN,NaN,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,0,No,NaN,NaN,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,0,Yes,4.3outof5,"Cocktails, Pizza, Buttermilk","2,500"
51716,The Nest - The Den Bengaluru,0,No,3.4outof5,NaN,"1,500"